[package]
name = "orio"
version = "0.1.0"
edition = "2021"

[dependencies]
trueblocks = {path = '../core'}
reqwest = { version = "0.12", features = ["json", "stream"] }
dirs = "5.0"
serde_json = "1.0"
rayon = "1.8"
futures = "0.3.0"
tokio = { version = "1", features = ["full"] }